--- Para consulta de compras de unidades

ALTER TABLE `IVF_ITMOP0` ADD UNIQUE (
`OPE_NROINT`
);

ALTER TABLE `PVD4_FACTU` ADD UNIQUE (
`FAC_NROINT`
);

ALTER TABLE STS_UNIDA0 ADD INDEX (
OPE_NUMERO
);