SELECT
  M.ART_STOCK AS Cantidad,
  MONTH(M.ART_FECHA) as Mes,
  YEAR(M.ART_FECHA) as Anio,
  X.ART_DESCRI as Descripcion,
  X.SUBGRUPO as Subgrupo,
  X.GRUPO as Grupo,
  X.MARCA as Marca
FROM
 STS_ARTIC0 A
 JOIN STS_MOVIM0 M ON (M.ART_CODIGO = A.ART_CODIGO)
 JOIN X_PROYECTO_VEHICULOS X ON (X.ART_CODIGO = A.ART_CODIGO)
WHERE
    A.ART_DEFCOD = 3
AND M.ART_DEFCOD = 3
AND X.ART_DEFCOD = 3
AND M.ART_TIPMOV ='s3'